# Generated by Django 3.0 on 2026-06-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
                ('image', models.CharField(default='', max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('BLOG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.Blog')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.Users')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.Users'),
        ),
    ]
