# Generated by Django 3.0 on 2026-06-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20260602_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
